# Generated by Django 3.1.4 on 2021-01-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Lekarz', models.IntegerField()),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Specjalizacja', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Uzytkownik', models.IntegerField()),
                ('Imie', models.CharField(max_length=45)),
                ('Nazwisko', models.CharField(max_length=45)),
                ('Login', models.CharField(max_length=45)),
                ('Haslo', models.CharField(max_length=45)),
                ('Mail', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Zwierze', models.IntegerField()),
                ('Imie', models.CharField(max_length=45)),
                ('Rasa', models.CharField(max_length=45)),
                ('Uzytkownik_id_Uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Wizyty', models.IntegerField()),
                ('Data', models.DateField()),
                ('Lekarz_id_Lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.lekarz')),
                ('Zwierze_id_Zwierze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.zwierze')),
            ],
        ),
        migrations.CreateModel(
            name='Recepty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Recepty', models.IntegerField()),
                ('Nazwa_Recepty', models.CharField(max_length=45)),
                ('Opis', models.CharField(max_length=45)),
                ('Lekarz_id_Lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='Operacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Operacje', models.IntegerField()),
                ('Nazwa', models.CharField(max_length=45)),
                ('Data', models.DateField()),
                ('Zwierze_id_Zwierze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.zwierze')),
            ],
        ),
        migrations.AddField(
            model_name='lekarz',
            name='Operacje_id_Operacje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KlinikaApp.operacje'),
        ),
    ]
